<!DOCTYPE html>
<!-- saved from url=(0022)http://localhost:3993/ -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" style="--vsc-domain: &quot;localhost&quot;;"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dana Kim">

<title>Analaysis of Social Media Engagement</title>
<style class="anchorjs"></style><style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="./Analaysis of Social Media Engagement_files/clipboard.min.js.download"></script>
<script src="./Analaysis of Social Media Engagement_files/quarto.js.download" type="module"></script>
<script src="./Analaysis of Social Media Engagement_files/tabsets.js.download" type="module"></script>
<script src="./Analaysis of Social Media Engagement_files/popper.min.js.download"></script>
<script src="./Analaysis of Social Media Engagement_files/tippy.umd.min.js.download"></script>
<script src="./Analaysis of Social Media Engagement_files/anchor.min.js.download"></script>
<link href="./Analaysis of Social Media Engagement_files/tippy.css" rel="stylesheet">
<link href="./Analaysis of Social Media Engagement_files/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="./Analaysis of Social Media Engagement_files/bootstrap.min.js.download"></script>
<link href="./Analaysis of Social Media Engagement_files/bootstrap-icons.css" rel="stylesheet">
<link href="./Analaysis of Social Media Engagement_files/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<style>.ansi-display{font-family:monospace;white-space:pre-wrap;--ansiBlack: #000000;--ansiRed: #cd3131;--ansiGreen: #00BC00;--ansiYellow: #949800;--ansiBlue: #0451a5;--ansiMagenta: #bc05bc;--ansiCyan: #0598bc;--ansiWhite: #555555;--ansiBrightBlack: #666666;--ansiBrightRed: #cd3131;--ansiBrightGreen: #14CE14;--ansiBrightYellow: #b5ba00;--ansiBrightBlue: #0451a5;--ansiBrightMagenta: #bc05bc;--ansiBrightCyan: #0598bc;--ansiBrightWhite: #a5a5a5}.dark-mode .ansi-display{--ansiBlack: #000000;--ansiRed: #cd3131;--ansiGreen: #0DBC79;--ansiYellow: #e5e510;--ansiBlue: #2472c8;--ansiMagenta: #bc3fbc;--ansiCyan: #11a8cd;--ansiWhite: #e5e5e5;--ansiBrightBlack: #666666;--ansiBrightRed: #f14c4c;--ansiBrightGreen: #23d18b;--ansiBrightYellow: #f5f543;--ansiBrightBlue: #3b8eea;--ansiBrightMagenta: #d670d6;--ansiBrightCyan: #29b8db;--ansiBrightWhite: #e5e5e5}@keyframes ansi-displaly-run-blink{50%{opacity:0}}.fui-FluentProvider h2{border-bottom:none;padding-bottom:0}</style><style data-make-styles-bucket="d" data-priority="0"></style><style id="fui-FluentProviderr0"></style></head>

<body class="fullcontent quarto-light" data-tabster="{&quot;root&quot;:{}}" data-new-gr-c-s-check-loaded="14.1266.0" data-gr-ext-installed="" data-fui-focus-visible="">

<i tabindex="0" role="none" data-tabster-dummy="" aria-hidden="true" style="position: fixed; height: 1px; width: 1px; opacity: 0.001; z-index: -1; content-visibility: hidden; top: 0px; left: 0px;"></i><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analaysis of Social Media Engagement</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dana Kim </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#setup" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>This chunk loads the required libraries and the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="http://localhost:3993/#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb1-2"><a href="http://localhost:3993/#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># For data manipulation and visualization</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="http://localhost:3993/#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)   <span class="co"># For spline modeling</span></span>
<span id="cb4-2"><a href="http://localhost:3993/#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)       <span class="co"># For Variance Inflation Factor (VIF) calculation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="http://localhost:3993/#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)      <span class="co"># For cross-validation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'boot'

The following object is masked from 'package:car':

    logit</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="http://localhost:3993/#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)     <span class="co"># For table formatting</span></span>
<span id="cb8-2"><a href="http://localhost:3993/#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="http://localhost:3993/#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data and prepare variables</span></span>
<span id="cb8-4"><a href="http://localhost:3993/#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The 'Date' column is converted to Date format.</span></span>
<span id="cb8-5"><a href="http://localhost:3993/#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The 'Day' column is converted to a factor with a specific order (Monday is the reference level).</span></span>
<span id="cb8-6"><a href="http://localhost:3993/#cb8-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"actscollegefellowship.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="http://localhost:3993/#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-8"><a href="http://localhost:3993/#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Date =</span> <span class="fu">as.Date</span>(Date, <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>),</span>
<span id="cb8-9"><a href="http://localhost:3993/#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Day =</span> <span class="fu">factor</span>(Day, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Monday"</span>, <span class="st">"Tuesday"</span>, <span class="st">"Wednesday"</span>, <span class="st">"Thursday"</span>, <span class="st">"Friday"</span>, <span class="st">"Saturday"</span>, <span class="st">"Sunday"</span>))</span>
<span id="cb8-10"><a href="http://localhost:3993/#cb8-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 113 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Date, Day
dbl (6): Views, Reach, Interactions, Link Clicks, Profile Visits, Follows

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="http://localhost:3993/#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a helper function to robustly extract p-values by searching the coefficient names</span></span>
<span id="cb10-2"><a href="http://localhost:3993/#cb10-2" aria-hidden="true" tabindex="-1"></a>robust_p_value <span class="ot">&lt;-</span> <span class="cf">function</span>(model, name_fragment) {</span>
<span id="cb10-3"><a href="http://localhost:3993/#cb10-3" aria-hidden="true" tabindex="-1"></a>  coefs <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients</span>
<span id="cb10-4"><a href="http://localhost:3993/#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Use grepl to find the row name containing the fragment (e.g., "Link Clicks")</span></span>
<span id="cb10-5"><a href="http://localhost:3993/#cb10-5" aria-hidden="true" tabindex="-1"></a>  row_index <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">grepl</span>(name_fragment, <span class="fu">rownames</span>(coefs))) </span>
<span id="cb10-6"><a href="http://localhost:3993/#cb10-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-7"><a href="http://localhost:3993/#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(row_index) <span class="sc">==</span> <span class="dv">1</span>) {</span>
<span id="cb10-8"><a href="http://localhost:3993/#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(coefs[row_index, <span class="st">"Pr(&gt;|t|)"</span>])</span>
<span id="cb10-9"><a href="http://localhost:3993/#cb10-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb10-10"><a href="http://localhost:3993/#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If the exact name is missed, return NA (or an error)</span></span>
<span id="cb10-11"><a href="http://localhost:3993/#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">NA</span>) </span>
<span id="cb10-12"><a href="http://localhost:3993/#cb10-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-13"><a href="http://localhost:3993/#cb10-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#introduction" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<section id="project-introduction" class="level3">
<h3 class="anchored" data-anchor-id="project-introduction">Project Introduction<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#project-introduction" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The objective of this project is to apply the concepts learned in this course to a real-world dataset, specifically to understand and model the factors influencing social media engagement. We will use the tools learned to understand the data, apply appropriate linear regression models, evaluate and improve these models, and present the results.</p>
</section>
<section id="dataset-source-and-description" class="level3">
<h3 class="anchored" data-anchor-id="dataset-source-and-description">Dataset Source and Description<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#dataset-source-and-description" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The dataset used for this analysis, contained in the file actscollegefellowship.csv, was collected directly from <strong>Meta Business Suite Insights</strong>. It tracks daily performance metrics of Instagram account <span class="citation" data-cites="actscollegefellowship">@actscollegefellowship</span>, over a period from August 19, 2025, to December 9, 2025, which accounts for Fall 2025 school semester. This research is valid because understanding and optimizing content reach is primary objective for maximizing the ministry’s impact and communication effectiveness, especially as the local church’s media/tech ministry leader.</p>
</section>
<section id="variables-and-observations" class="level3">
<h3 class="anchored" data-anchor-id="variables-and-observations">Variables and Observations<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#variables-and-observations" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The dataset contains 113 observations (rows), with each row representing the metrics for a single day. It includes seven primary variables, meeting the requirement of at least five variables, with at least one categroical and three numerical variables:</p>
<ul>
<li><strong><em>Output Variable (Y): Views.</em></strong> This is a numeric outcome metric.</li>
<li><strong><em>Predictor/Independent Variables (X):</em></strong>
<ul>
<li><strong><em>Day</em></strong> (Categorical, 7 levels)</li>
<li><strong><em>Reach</em></strong> (Numeric)</li>
<li><strong><em>Interactions</em></strong> (Numeric)</li>
<li><strong><em>Link Clicks</em></strong> (Numeric)</li>
<li><strong><em>Profile Visits</em></strong> (Numeric)</li>
<li><strong><em>Follows</em></strong> (Numeric)</li>
</ul></li>
</ul>
<p>All numeric variables take on more than 10 distinct values, and the categorical variables has at least three levels, satisfying the project requirements.</p>
</section>
<section id="group-observation-count-for-categorical-variable" class="level3">
<h3 class="anchored" data-anchor-id="group-observation-count-for-categorical-variable">Group Observation Count for Categorical Variable<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#group-observation-count-for-categorical-variable" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The number of observations per group for the categorical variable <strong>Day</strong> are calculated below, fulfilling the requirment to report observation counts per group:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="http://localhost:3993/#cb11-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="http://localhost:3993/#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Day) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="http://localhost:3993/#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="ot">=</span> Day, <span class="at">Count =</span> n) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="http://localhost:3993/#cb11-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Day of Week</th>
<th style="text-align: right;">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Monday</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tuesday</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wednesday</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thursday</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Friday</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saturday</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sunday</td>
<td style="text-align: right;">16</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#research-questions" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>We specify at least three scientific hypotheses (research questions) we are interested in assesing. This is done prior to fitting any models or doing any visualizations.</p>
<p><strong><em>Hypothesis 1: Day of the Week Effect on Views</em></strong></p>
<ul>
<li><strong>Claim:</strong> Content posted on certain days of the week, specifically during the weekend (Saturday and Sunday), will generate higher Views compared to weekdays.</li>
</ul>
<p><strong><em>Hypothesis 2: Quality of Engagement Drives Views</em></strong></p>
<ul>
<li><strong>Claim:</strong> The quality metric Interactions will have a strong positive correlation with Views, as higher interactions often lead to greater algorithmic distribution ad increased Views.</li>
</ul>
<p><strong><em>Hypothesis 3: Funnel Metrics Predict Views</em></strong></p>
<ul>
<li><strong>Claim:</strong> Actions lower in the engagement funnel, like Link Clicks, will be a significant predictor of Views</li>
</ul>
</section>
<section id="data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration">Data Exploration<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#data-exploration" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>We use visualizations (scatterplots and boxplots) to visually assess the marginal relationships between each of our predictors and the numeric outcomes (Views).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="http://localhost:3993/#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate predictor names</span></span>
<span id="cb12-2"><a href="http://localhost:3993/#cb12-2" aria-hidden="true" tabindex="-1"></a>numeric_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Reach"</span>, <span class="st">"Interactions"</span>, <span class="st">"Link Clicks"</span>, <span class="st">"Profile Visits"</span>, <span class="st">"Follows"</span>)</span>
<span id="cb12-3"><a href="http://localhost:3993/#cb12-3" aria-hidden="true" tabindex="-1"></a>outcome_var <span class="ot">&lt;-</span> <span class="st">"Views"</span></span>
<span id="cb12-4"><a href="http://localhost:3993/#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="http://localhost:3993/#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplots for Numeric Predictors vs. Views</span></span>
<span id="cb12-6"><a href="http://localhost:3993/#cb12-6" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="http://localhost:3993/#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(outcome_var), <span class="fu">all_of</span>(numeric_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="http://localhost:3993/#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(numeric_vars), <span class="at">names_to =</span> <span class="st">"Predictor"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="http://localhost:3993/#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> Views)) <span class="sc">+</span></span>
<span id="cb12-10"><a href="http://localhost:3993/#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="http://localhost:3993/#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb12-12"><a href="http://localhost:3993/#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Predictor, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb12-13"><a href="http://localhost:3993/#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplots of Numeric Predictors vs. Views"</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="http://localhost:3993/#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="./Analaysis of Social Media Engagement_files/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="http://localhost:3993/#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot for Categorical Predictor (Day) vs. Views</span></span>
<span id="cb14-2"><a href="http://localhost:3993/#cb14-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="http://localhost:3993/#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Day, <span class="at">y =</span> Views, <span class="at">fill =</span> Day)) <span class="sc">+</span></span>
<span id="cb14-4"><a href="http://localhost:3993/#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-5"><a href="http://localhost:3993/#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Views by Day of the Week"</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="http://localhost:3993/#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-7"><a href="http://localhost:3993/#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="./Analaysis of Social Media Engagement_files/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="http://localhost:3993/#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Numerical Summaries for Data Exploration ---</span></span>
<span id="cb15-2"><a href="http://localhost:3993/#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="http://localhost:3993/#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantitative Assessment (Correlation for Numeric Variables)</span></span>
<span id="cb15-4"><a href="http://localhost:3993/#cb15-4" aria-hidden="true" tabindex="-1"></a>views_correlations <span class="ot">&lt;-</span> <span class="fu">cor</span>(df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">all_of</span>(numeric_vars), <span class="fu">all_of</span>(outcome_var)), <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)[outcome_var, numeric_vars]</span>
<span id="cb15-5"><a href="http://localhost:3993/#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Pearson Correlation with Views:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pearson Correlation with Views:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="http://localhost:3993/#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">sort</span>(views_correlations, <span class="at">decreasing =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Reach Profile Visits   Interactions        Follows    Link Clicks 
     0.9337316      0.9163494      0.8596353      0.6167599      0.1857272 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="http://localhost:3993/#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary Statistics for Views by Day (for Boxplot Analysis)</span></span>
<span id="cb19-2"><a href="http://localhost:3993/#cb19-2" aria-hidden="true" tabindex="-1"></a>summary_views_by_day <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="http://localhost:3993/#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Day) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="http://localhost:3993/#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-5"><a href="http://localhost:3993/#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Count =</span> <span class="fu">n</span>(),</span>
<span id="cb19-6"><a href="http://localhost:3993/#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_Views =</span> <span class="fu">min</span>(Views),</span>
<span id="cb19-7"><a href="http://localhost:3993/#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q1_Views =</span> <span class="fu">quantile</span>(Views, <span class="fl">0.25</span>),</span>
<span id="cb19-8"><a href="http://localhost:3993/#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median_Views =</span> <span class="fu">median</span>(Views),</span>
<span id="cb19-9"><a href="http://localhost:3993/#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Q3_Views =</span> <span class="fu">quantile</span>(Views, <span class="fl">0.75</span>),</span>
<span id="cb19-10"><a href="http://localhost:3993/#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_Views =</span> <span class="fu">max</span>(Views),</span>
<span id="cb19-11"><a href="http://localhost:3993/#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">IQR =</span> Q3_Views <span class="sc">-</span> Q1_Views</span>
<span id="cb19-12"><a href="http://localhost:3993/#cb19-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="http://localhost:3993/#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Median_Views)</span>
<span id="cb19-14"><a href="http://localhost:3993/#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="http://localhost:3993/#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n\n</span><span class="st">### Summary Statistics for Views by Day</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

### Summary Statistics for Views by Day</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="http://localhost:3993/#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Format and print the summary statistics as Markdown table content using cat()</span></span>
<span id="cb21-2"><a href="http://localhost:3993/#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">kable</span>(summary_views_by_day, <span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">digits =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>|Day       | Count| Min_Views| Q1_Views| Median_Views| Q3_Views| Max_Views|     IQR| |:---------|-----:|---------:|--------:|------------:|--------:|---------:|-------:| |Thursday  |    16|       258|   368.25|        701.0|  2581.75|     12855| 2213.50| |Wednesday |    16|       143|   537.25|        769.5|  2644.25|      8375| 2107.00| |Friday    |    16|       175|   487.25|        929.0|  1746.75|      7766| 1259.50| |Tuesday   |    17|       287|   639.00|       1186.0|  1939.00|      8105| 1300.00| |Monday    |    16|       344|   783.50|       1319.0|  1804.25|     13994| 1020.75| |Sunday    |    16|       337|  1167.50|       1507.0|  2381.75|      4904| 1214.25| |Saturday  |    16|       371|   606.75|       1883.5|  3597.75|      6198| 2991.00|</code></pre>
</div>
</div>
<p>The scatterplots reveal a strong, positive, and seemingly non-linear relationship between <strong>Views</strong> and <strong>Reach, Interactions, Profile Visits</strong>. The highest Pearson correlation is found with <strong>Reach</strong> (r ≈ 0.90), <strong>Reach</strong> is the predictor that seems to be most highly correlated with the outcome of interest because a “View” is an event <em>after</em> content has reached a unique account, making Reach a direct precursor to Views.</p>
<p>The boxplot analysis for <strong>Views by Day of the Week</strong> shows that:</p>
<ul>
<li><strong><em>Weekend Performance:</em></strong> The median number of View is highest on <strong>Saturday</strong> (1883.5) and <strong>Sunday</strong> (1507.0), providing initial support for Hypothesis 1.</li>
<li><strong><em>Lowest Performance:</em></strong> Median Views are lowest mid-week on <strong>Thursday</strong> (701.0) and <strong>Wednesday</strong> (769.5),</li>
<li><strong><em>Variability and Outliers:</em></strong> <strong>Saturday</strong> exhibits the highest Interquartile Range (IQR ≈ 2991), indicating the most variation in typical daily performance. <strong>Monday</strong> has the highest maximum value (13994), suggesting a major outlier day that is likely to be highly influential in the regression model.</li>
</ul>
</section>
<section id="multiple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-model">Multiple Linear Regression Model<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#multiple-linear-regression-model" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>We fit a multiple linear regression model to predict the chosen outcome from the seet of numeric and categorical predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="http://localhost:3993/#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the initial Multiple Linear Regression Model</span></span>
<span id="cb23-2"><a href="http://localhost:3993/#cb23-2" aria-hidden="true" tabindex="-1"></a>model_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(Views <span class="sc">~</span> Reach <span class="sc">+</span> Interactions <span class="sc">+</span> <span class="st">`</span><span class="at">Link Clicks</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Profile Visits</span><span class="st">`</span> <span class="sc">+</span> Follows <span class="sc">+</span> Day, <span class="at">data =</span> df)</span>
<span id="cb23-3"><a href="http://localhost:3993/#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="http://localhost:3993/#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the model</span></span>
<span id="cb23-5"><a href="http://localhost:3993/#cb23-5" aria-hidden="true" tabindex="-1"></a>model_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_full)</span>
<span id="cb23-6"><a href="http://localhost:3993/#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Views ~ Reach + Interactions + `Link Clicks` + `Profile Visits` + 
    Follows + Day, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-2403.73  -277.66   -45.18   305.71  2343.85 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       98.1483   198.1659   0.495  0.62148    
Reach              1.7436     0.3651   4.775 6.09e-06 ***
Interactions      12.0109     3.0173   3.981  0.00013 ***
`Link Clicks`     11.1809    14.6722   0.762  0.44781    
`Profile Visits`  17.8061     3.3929   5.248 8.52e-07 ***
Follows          137.9912    45.5934   3.027  0.00314 ** 
DayTuesday       -99.8333   238.7931  -0.418  0.67678    
DayWednesday     -61.5698   241.4775  -0.255  0.79926    
DayThursday      157.2408   242.2928   0.649  0.51783    
DayFriday        193.9990   240.1773   0.808  0.42114    
DaySaturday       44.2509   246.2179   0.180  0.85773    
DaySunday        -18.3307   242.6880  -0.076  0.93994    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 674.9 on 101 degrees of freedom
Multiple R-squared:  0.9301,    Adjusted R-squared:  0.9225 
F-statistic: 122.2 on 11 and 101 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="interpretation-of-slope-estimates" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-slope-estimates">Interpretation of Slope Estimates<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#interpretation-of-slope-estimates" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The slopes have different interpretations depending on the variable type, holding all other predictors constant.</p>
<ul>
<li>For <strong>Numeric Predictors</strong> (e.g.&nbsp;Reach): The estimated slope represents the average change in <strong>Views</strong> for a one-unit increase in the predictor</li>
<li>For the <strong>Categorical Predictor</strong> (Day): The estimated slope for a level(e.g.&nbsp;DayTuesday) represents the average difference in <strong>Views</strong> for that level compared to the <strong>baseline level (Monday)</strong></li>
</ul>
</section>
<section id="overall-f-test-for-model-significance" class="level3">
<h3 class="anchored" data-anchor-id="overall-f-test-for-model-significance">Overall F-Test for Model Significance<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#overall-f-test-for-model-significance" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>We perform the overall F-test for model significance.</p>
<ul>
<li><strong>Null Hypothesis (H<sub>0</sub>): <em>B<sub>Reach</sub></em> = <em>B<sub>Interactions</sub></em> = … = <em>B<sub>DaySunday</sub></em> = 0</strong></li>
<li><strong>Alternative Hypothesis (H<sub>A</sub>):</strong> At least one of the regression coefficients (B<sub>j</sub>) is not zero.</li>
</ul>
<p>The F-statistic from the model summary is 122.2 with an associated P-value of &lt; 2.2e-16. Since the P-value is extremely small, we reject the null hypothesis. We conclude that the overall linear regression model is statistically significant.</p>
</section>
<section id="interpretation-of-multiple-r-squared" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-multiple-r-squared">Interpretation of Multiple R-squared<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#interpretation-of-multiple-r-squared" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The Multiple R-squared is 0.9301. This value indicates that approximately 93.01% of the total variance in <strong>Views</strong> is explained by the full set of predictors in this model.</p>
</section>
<section id="residual-standard-error" class="level3">
<h3 class="anchored" data-anchor-id="residual-standard-error">Residual Standard Error<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#residual-standard-error" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The Residual Standard Error (RSE) is 674.9. This value is related to the accuracy of the model in forming its predictions; it suggests that the predicted number of Views tend to be, on average, about 675 units away from the actual observed number of Views.</p>
</section>
</section>
<section id="improving-the-model" class="level2">
<h2 class="anchored" data-anchor-id="improving-the-model">Improving the Model<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#improving-the-model" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>We use diagnostic plots to assess whether any of the underlying linear regression assumptions are violated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="http://localhost:3993/#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot initial diagnostic plots (Visual Inspection Required)</span></span>
<span id="cb25-2"><a href="http://localhost:3993/#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_full, <span class="at">which =</span> <span class="dv">1</span>) <span class="co"># Residuals vs. Fitted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="./Analaysis of Social Media Engagement_files/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="transformation" class="level3">
<h3 class="anchored" data-anchor-id="transformation">Transformation<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#transformation" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>Visual inspection of the <strong>Residual vs.&nbsp;Fitted</strong> plot for model_full suggests a violation of <strong>constant variance (homoscedasticity)</strong> assumption. To fix this, we apply a <strong>log transformation</strong> to the outcome variable, Views.</p>
<p>The original model had an R-squared of 0.9301 and an RSE of 674.9.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="http://localhost:3993/#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the transformed model</span></span>
<span id="cb26-2"><a href="http://localhost:3993/#cb26-2" aria-hidden="true" tabindex="-1"></a>model_transformed <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Views) <span class="sc">~</span> Reach <span class="sc">+</span> Interactions <span class="sc">+</span> <span class="st">`</span><span class="at">Link Clicks</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Profile Visits</span><span class="st">`</span> <span class="sc">+</span> Follows <span class="sc">+</span> Day, <span class="at">data =</span> df)</span>
<span id="cb26-3"><a href="http://localhost:3993/#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="http://localhost:3993/#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-assess diagnostic plots for the transformed model</span></span>
<span id="cb26-5"><a href="http://localhost:3993/#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_transformed, <span class="at">which =</span> <span class="dv">1</span>) <span class="co"># Residuals vs. Fitted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="./Analaysis of Social Media Engagement_files/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The diagnostic plots for model_transformed show improved adherence to the assumptions. The transformed model has an R-squared of 0.7750 and a Residual Standard Error (RSE) of 0.4972 (on the long scale).</p>
</section>
<section id="incorporating-a-spline-term" class="level3">
<h3 class="anchored" data-anchor-id="incorporating-a-spline-term">Incorporating a Spline Term<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#incorporating-a-spline-term" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>We consider replacing the linear term for <strong>Reach</strong> with a cubic spline using bs() from the splines library.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="http://localhost:3993/#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model with a cubic spline (df=3) for Reach</span></span>
<span id="cb27-2"><a href="http://localhost:3993/#cb27-2" aria-hidden="true" tabindex="-1"></a>model_spline <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Views) <span class="sc">~</span> <span class="fu">bs</span>(Reach, <span class="at">df=</span><span class="dv">3</span>) <span class="sc">+</span> Interactions <span class="sc">+</span> <span class="st">`</span><span class="at">Link Clicks</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Profile Visits</span><span class="st">`</span> <span class="sc">+</span> Follows <span class="sc">+</span> Day, <span class="at">data =</span> df)</span>
<span id="cb27-3"><a href="http://localhost:3993/#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="http://localhost:3993/#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test the inclusion of the spline term using an ANOVA</span></span>
<span id="cb27-5"><a href="http://localhost:3993/#cb27-5" aria-hidden="true" tabindex="-1"></a>test_spline <span class="ot">&lt;-</span> <span class="fu">anova</span>(model_transformed, model_spline)</span>
<span id="cb27-6"><a href="http://localhost:3993/#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test_spline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(Views) ~ Reach + Interactions + `Link Clicks` + `Profile Visits` + 
    Follows + Day
Model 2: log(Views) ~ bs(Reach, df = 3) + Interactions + `Link Clicks` + 
    `Profile Visits` + Follows + Day
  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1    101 24.971                                
2     99 21.729  2    3.2424 7.3864 0.001023 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The ANOVA test yields an F-statistic of 7.3864 and a P-value of 0.001023. Since P &lt; 0.05m the inclusion of the cubic spline for <strong>Reach</strong> is statistically justified. This suggests the marginal relationship between log(Views) and Reach is significantly non-linear. Although its inclusion is supported, we will continue using the simpler model_transformed for subsequent interpretation ease, but the finding itself represents a significant model improvement step.</p>
</section>
<section id="hypothesizing-and-testing-with-an-interaction-term" class="level3">
<h3 class="anchored" data-anchor-id="hypothesizing-and-testing-with-an-interaction-term">Hypothesizing and Testing with an Interaction Term<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#hypothesizing-and-testing-with-an-interaction-term" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p><strong><em>Hypothesis:</em></strong> We hypothesize an interaction between <strong>Interactions</strong> and <strong>Profile Visits</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="http://localhost:3993/#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model with the interaction term</span></span>
<span id="cb29-2"><a href="http://localhost:3993/#cb29-2" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Views) <span class="sc">~</span> Reach <span class="sc">+</span> Interactions <span class="sc">*</span> <span class="st">`</span><span class="at">Profile Visits</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Link Clicks</span><span class="st">`</span> <span class="sc">+</span> Follows <span class="sc">+</span> Day, <span class="at">data =</span> df)</span>
<span id="cb29-3"><a href="http://localhost:3993/#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="http://localhost:3993/#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test the inclusion of the interaction using an ANOVA</span></span>
<span id="cb29-5"><a href="http://localhost:3993/#cb29-5" aria-hidden="true" tabindex="-1"></a>test_interaction <span class="ot">&lt;-</span> <span class="fu">anova</span>(model_transformed, model_interaction)</span>
<span id="cb29-6"><a href="http://localhost:3993/#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(Views) ~ Reach + Interactions + `Link Clicks` + `Profile Visits` + 
    Follows + Day
Model 2: log(Views) ~ Reach + Interactions * `Profile Visits` + `Link Clicks` + 
    Follows + Day
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    101 24.971                                  
2    100 20.862  1    4.1096 19.699 2.337e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This ANOVA test yields an F-statistic of 19.699 and a P-value of 2.337e-05. Since P &lt; 0.05, the interaction term is <strong>statistically significant.</strong> This indicates that the effect of Interactions on log(Views) depends significantly on the number of Profile Visits.</p>
</section>
</section>
<section id="formal-hypothesis-tests" class="level2">
<h2 class="anchored" data-anchor-id="formal-hypothesis-tests">Formal Hypothesis Tests<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#formal-hypothesis-tests" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>We formalize the hypotheses from Section 1 and perform hypothesis tests using the appropriate R functions. We use a cutoff of 0.05 for the P-value. <em>(We use the simpler transformed additive model as the base for these tests to focus on main effects, despite the supported non-linear and interaction terms)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="http://localhost:3993/#cb31-1" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span> model_transformed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="testing-hypothesis-1-day-of-the-week-effect" class="level3">
<h3 class="anchored" data-anchor-id="testing-hypothesis-1-day-of-the-week-effect">Testing Hypothesis 1: Day of the Week Effect<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#testing-hypothesis-1-day-of-the-week-effect" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<ul>
<li><strong>Formal Hypotheses:</strong>
<ul>
<li><strong>H<sub>0</sub>:</strong> <em>B<sub>Tuesday</sub></em> = … <em>B<sub>Sunday</sub></em> = 0 (The factor ‘Day’ has no effect)</li>
<li><strong>H<sub>A</sub>:</strong> At least one <em>B<sub>Dayj</sub></em> ≠ 0</li>
</ul></li>
<li><strong>Test:</strong> We use ANOVA to drop the entire Day factor.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="http://localhost:3993/#cb32-1" aria-hidden="true" tabindex="-1"></a>model_no_day <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Views) <span class="sc">~</span> Reach <span class="sc">+</span> Interactions <span class="sc">+</span> <span class="st">`</span><span class="at">Link Clicks</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Profile Visits</span><span class="st">`</span> <span class="sc">+</span> Follows, <span class="at">data =</span> df)</span>
<span id="cb32-2"><a href="http://localhost:3993/#cb32-2" aria-hidden="true" tabindex="-1"></a>test_h1 <span class="ot">&lt;-</span> <span class="fu">anova</span>(model_no_day, final_model)</span>
<span id="cb32-3"><a href="http://localhost:3993/#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test_h1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(Views) ~ Reach + Interactions + `Link Clicks` + `Profile Visits` + 
    Follows
Model 2: log(Views) ~ Reach + Interactions + `Link Clicks` + `Profile Visits` + 
    Follows + Day
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    107 26.834                           
2    101 24.971  6    1.8622 1.2553 0.2849</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="http://localhost:3993/#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conclusion:</span></span>
<span id="cb34-2"><a href="http://localhost:3993/#cb34-2" aria-hidden="true" tabindex="-1"></a>p_value_h1 <span class="ot">&lt;-</span> test_h1<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The P-value for dropping the entire Day factor is 0.2849, SInce this is greater than 0.05, we <strong>fail to reject the null hypothesis</strong>. The results <strong>fail to support</strong> the informal hypotheiss that the day of the week is a significant predictor of log(Views) when controlling for other metrics.</p>
</section>
<section id="testing-hypothesis-2-interaction-drives-views" class="level3">
<h3 class="anchored" data-anchor-id="testing-hypothesis-2-interaction-drives-views">Testing Hypothesis 2: Interaction Drives Views<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#testing-hypothesis-2-interaction-drives-views" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<ul>
<li><strong>Formal Hypotheses:</strong>
<ul>
<li><strong>H<sub>0</sub>:</strong> <em>B<sub>Interactions</sub></em> = 0</li>
<li><strong>H<sub>A</sub>:</strong> <em>B<sub>Interactions</sub></em> ≠ 0</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="http://localhost:3993/#cb35-1" aria-hidden="true" tabindex="-1"></a>p_value_interactions <span class="ot">&lt;-</span> <span class="fu">summary</span>(final_model)<span class="sc">$</span>coefficients[<span class="st">"Interactions"</span>, <span class="st">"Pr(&gt;|t|)"</span>]</span>
<span id="cb35-2"><a href="http://localhost:3993/#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"P-value for Interactions:"</span>, <span class="fu">round</span>(p_value_interactions, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P-value for Interactions: 0.4313"</code></pre>
</div>
</div>
</section>
<section id="testing-hypothesis-3-funnel-metrics-predict-views" class="level3">
<h3 class="anchored" data-anchor-id="testing-hypothesis-3-funnel-metrics-predict-views">Testing Hypothesis 3: Funnel Metrics Predict Views<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#testing-hypothesis-3-funnel-metrics-predict-views" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The P-value for Interactions is 0.4313. Since this is greater than 0.05, we <strong>fail to reject the null hypothesis</strong>. The results fail to support the informal hypothesis that a greater number of <strong>Interactions</strong> is significantly associated with an increase in log(Views).</p>
<ul>
<li><strong>Formal Hypotheses:</strong>
<ul>
<li><strong>H<sub>0</sub>:</strong> <em>B<sub>LinkClicks</sub></em> = 0</li>
<li><strong>H<sub>A</sub>:</strong> <em>B<sub>LinkClicks</sub></em> ≠ 0</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="http://localhost:3993/#cb37-1" aria-hidden="true" tabindex="-1"></a>p_value_links <span class="ot">&lt;-</span> <span class="fu">robust_p_value</span>(final_model, <span class="st">"Link Clicks"</span>)</span>
<span id="cb37-2"><a href="http://localhost:3993/#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"P-value for Link Clicks:"</span>, <span class="fu">round</span>(p_value_links, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P-value for Link Clicks: 0.1898"</code></pre>
</div>
</div>
<p>The P-value for Link Clicks is 0.1898. Since this is greater than 0.05m we <strong>fail to reject the null hypothesis</strong>. The results <strong>fail to support</strong> the informal hypothesis that <strong>Link Clicks</strong> is a significant predictor of log(Views).</p>
</section>
<section id="limitations-to-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="limitations-to-conclusions">Limitations to Conclusions<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#limitations-to-conclusions" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>A key limitation to our conclusion is the potential for <strong>omitted variable bias</strong>. However, the most significant constraints on the interpretation and generalizability of these results are tied to the <strong>characteristics of the social media account itself</strong>:</p>
<ul>
<li><strong><em>Small Account Size and Low Volume:</em></strong> The account is relatively small, with approximately 450 followers, and the dataset is limited to only 113 days of observation. The data points represent a relatively niche audience, and engagement metrics are often dominated by a few viral posts rather than consistent performance (as indicated by the outliers in the Boxplot Analysis). Conclusions drawn here may <strong>not be generalizable</strong> to accounts with higher posting volumes.</li>
<li><strong><em>Irregular Posting Schedule:</em></strong> The account does not follow a strict, regular posting schedule. This <strong>irregularity introduces noise</strong> into the Day factor. An irregular schedule means the audience may not form a strong expectation for content, reducing, the statistical power to detect a true underlying “best time to post” effect.</li>
<li><strong><em>High Multicollinearity:</em></strong> The presence of high Variance Inflation Factors (VIF) between core predictors like <strong>Reach</strong> and <strong>Interactions</strong> means that while the model is excellent at predicting <strong>Views</strong> (R-squred = 0.7750), we cannot reliably isolate the unique casual effect of one variable from the other.</li>
<li><strong><em>Justification Despite Limitations:</em></strong> <strong>Despite these statistical and structural limitations, the analysis remains valid because our primary goal is not to achieve perfect statistical inference but to spread the message of Gospel through this Instagram account effectively.</strong> The findings, especially regarding the highly significant non-linear relationships, provide actionable intelligence for future content strategy.</li>
</ul>
</section>
</section>
<section id="robustness-of-results" class="level2">
<h2 class="anchored" data-anchor-id="robustness-of-results">Robustness of Results<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#robustness-of-results" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
</section>
<section id="highly-influential-points" class="level2">
<h2 class="anchored" data-anchor-id="highly-influential-points">Highly Influential Points<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#highly-influential-points" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<p>We revisit the output of autoplot to check for any high influential points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="http://localhost:3993/#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(final_model, <span class="at">which =</span> <span class="dv">4</span>) <span class="co"># Plot of Residuals vs. Leverage (Cook's distance)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="./Analaysis of Social Media Engagement_files/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Residuals vs.&nbsp;Leverage plot highlights observations with high leverage and high Cook’s distance. These influential observations, which correspond to days with extremely high engagement metrics, influence the position of the regression plane.</p>
<section id="multicollinearity-of-predictors" class="level3">
<h3 class="anchored" data-anchor-id="multicollinearity-of-predictors">Multicollinearity of Predictors<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#multicollinearity-of-predictors" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>We compute Variance Inflation Factors (VIF) for each of the predictors to assess potential issues with multicollinearity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="http://localhost:3993/#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Variance Inflation Factors (VIF):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Variance Inflation Factors (VIF):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="http://localhost:3993/#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(final_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     GVIF Df GVIF^(1/(2*Df))
Reach            8.710253  1        2.951314
Interactions     5.096326  1        2.257504
`Link Clicks`    1.416552  1        1.190190
`Profile Visits` 5.757515  1        2.399482
Follows          2.136877  1        1.461806
Day              1.260388  6        1.019472</code></pre>
</div>
</div>
</section>
<section id="cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="cross-validation">Cross-Validation<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#cross-validation" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>We use cross-validation to estimate the leave-one-out (LOO) prediction error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="http://localhost:3993/#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use glm() for compatibility with cv.glm()</span></span>
<span id="cb44-2"><a href="http://localhost:3993/#cb44-2" aria-hidden="true" tabindex="-1"></a>final_model_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">log</span>(Views) <span class="sc">~</span> Reach <span class="sc">+</span> Interactions <span class="sc">+</span> <span class="st">`</span><span class="at">Link Clicks</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Profile Visits</span><span class="st">`</span> <span class="sc">+</span> Follows <span class="sc">+</span> Day, <span class="at">data =</span> df)</span>
<span id="cb44-3"><a href="http://localhost:3993/#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="http://localhost:3993/#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define cost function (Mean Squared Error)</span></span>
<span id="cb44-5"><a href="http://localhost:3993/#cb44-5" aria-hidden="true" tabindex="-1"></a>cost <span class="ot">&lt;-</span> <span class="cf">function</span>(r, <span class="at">pi =</span> <span class="dv">0</span>) <span class="fu">mean</span>((r <span class="sc">-</span> pi)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-6"><a href="http://localhost:3993/#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="http://localhost:3993/#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Leave-One-Out Cross-Validation</span></span>
<span id="cb44-8"><a href="http://localhost:3993/#cb44-8" aria-hidden="true" tabindex="-1"></a>cv_result <span class="ot">&lt;-</span> <span class="fu">cv.glm</span>(df, final_model_glm, <span class="at">cost =</span> cost, <span class="at">K =</span> <span class="fu">nrow</span>(df))</span>
<span id="cb44-9"><a href="http://localhost:3993/#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="http://localhost:3993/#cb44-10" aria-hidden="true" tabindex="-1"></a>LOO_prediction_error <span class="ot">&lt;-</span> cv_result<span class="sc">$</span>delta[<span class="dv">1</span>]</span>
<span id="cb44-11"><a href="http://localhost:3993/#cb44-11" aria-hidden="true" tabindex="-1"></a>RSE_log_scale_squared <span class="ot">&lt;-</span> <span class="fl">0.2472</span> <span class="co"># RSE squared (MSE) for the transformed model</span></span>
<span id="cb44-12"><a href="http://localhost:3993/#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="http://localhost:3993/#cb44-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"LOO Prediction Error (on log scale):"</span>, <span class="fu">round</span>(LOO_prediction_error, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "LOO Prediction Error (on log scale): 0.2933"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="http://localhost:3993/#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Residual Mean Squared Error (on log scale):"</span>, <span class="fu">round</span>(RSE_log_scale_squared, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Residual Mean Squared Error (on log scale): 0.2472"</code></pre>
</div>
</div>
<p>The LOO Prediction Error (r round(LOO_prediction_error, 4)) is very close to the Residual Mean Squared Error (0.2472). This suggests there is <strong>no evidence that the model is overfit</strong>.</p>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#conclusions" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h2>
<section id="automatic-model-selection" class="level3">
<h3 class="anchored" data-anchor-id="automatic-model-selection">Automatic Model Selection<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#automatic-model-selection" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>We perform <strong>Backward Selection</strong> based on the Akaike Information Criterion (AIC).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="http://localhost:3993/#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Backward Selection (based on AIC)</span></span>
<span id="cb48-2"><a href="http://localhost:3993/#cb48-2" aria-hidden="true" tabindex="-1"></a>model_backward <span class="ot">&lt;-</span> <span class="fu">step</span>(final_model, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb48-3"><a href="http://localhost:3993/#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="http://localhost:3993/#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the selected model</span></span>
<span id="cb48-5"><a href="http://localhost:3993/#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(model_backward))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Views) ~ `Profile Visits`, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.44966 -0.30451  0.05521  0.40203  0.90917 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      6.106739   0.072652   84.05   &lt;2e-16 ***
`Profile Visits` 0.019110   0.001048   18.24   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5002 on 111 degrees of freedom
Multiple R-squared:  0.7498,    Adjusted R-squared:  0.7475 
F-statistic: 332.6 on 1 and 111 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="selected-model" class="level3">
<h3 class="anchored" data-anchor-id="selected-model">Selected Model<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#selected-model" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The model selected by backward selection include the following predictors: <strong>Reach, Interactions, and Profile Visits</strong>.</p>
</section>
<section id="comment-on-the-limitations-of-automatic-model-selection" class="level3">
<h3 class="anchored" data-anchor-id="comment-on-the-limitations-of-automatic-model-selection">Comment on the Limitations of Automatic Model Selection<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#comment-on-the-limitations-of-automatic-model-selection" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>Automatic model selection is data-driven process that cna lead to P-values in the final model that are biased and understated.</p>
</section>
<section id="summary-of-what-was-learned" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-what-was-learned">Summary of What Was Learned<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#summary-of-what-was-learned" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<p>The log-transformed multiple linear regression model is highly effective (R-squared = 0.7750).</p>
<ul>
<li><strong><em>Marginal Significance:</em></strong> A simple linear regression showed <strong>Profile VIsits</strong> is highly significant predictor of log(Views) (R-squared = 0.7498, P &lt; 2.2e-16).</li>
<li><strong><em>Model Complexity:</em></strong> Both a non-linear relationship with <strong>Reach</strong> (P-value = 0.001023) and an interaction between <strong>Interactions</strong> and <strong>Profile Visits</strong> (P-value = 2.337e-05) are statistically significant.</li>
<li><strong><em>Multicollinearity and Core Hypotheses:</em></strong> Due to severe multicollinearity, none of the core hypotheses tested within the additive multiple regression model (H1, H2, H3) were supported by the formal t-tests, highlighting the statistical difficulty in separating the individual contributions of correlated engagement metrics.</li>
</ul>
</section>
<section id="future-avenues-for-research" class="level3">
<h3 class="anchored" data-anchor-id="future-avenues-for-research">Future Avenues for Research<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="http://localhost:3993/#future-avenues-for-research" style="font: 1em / 1 anchorjs-icons; margin-left: 0.1875em; padding-right: 0.1875em; padding-left: 0.1875em;"></a></h3>
<ol type="1">
<li><strong><em>Modeling Content Factors:</em></strong> Future research should incorporate additional predictors related to the <strong>content itself</strong> (e.g., video duration, post type) to explain the remaining variability.</li>
<li><strong><em>Addressing Multicollinearity:</em></strong> Use <strong>Principal Component Regression (PCR)</strong> to address the observed multicollinearity between Reach and Interactions, potentially leading to a more stable and interpretable model.</li>
<li><strong><em>Time Series Analysis:</em></strong> Given the data is sequential, future work should employ time series methods to model the underlying temporal structure of the data and account for autocorrelation in the residuals.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->





<script>
  window.backupDefine = window.define;
  window.define = undefined;
</script>
<script type="text/javascript" src="./Analaysis of Social Media Engagement_files/quarto-preview.js.download"></script>
<script>
  window.define = window.backupDefine;
  window.backupDefine = undefined;
</script>
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function () {
    window.QuartoPreview.init({
      origin: "",
      search: "",
      inputFile: "C:\Users\idian\OneDrive\Documents\index.qmd",
      isPresentation: false
    });
  })
</script>
<div><div dir="ltr" class="fui-FluentProvider fui-FluentProviderr0 ___jdtuxv0 f19n0e5 fxugw4r f1o700av fk6fouc fkhj508 figsok6 f1i3iumi"></div></div><i tabindex="0" role="none" data-tabster-dummy="" aria-hidden="true" style="position: fixed; height: 1px; width: 1px; opacity: 0.001; z-index: -1; content-visibility: hidden; top: 0px; left: 0px;"></i></body><grammarly-desktop-integration data-grammarly-shadow-root="true"><template shadowrootmode="open"><style>
      div.grammarly-desktop-integration {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        white-space: nowrap;
        border: 0;
        -moz-user-select: none;
        -webkit-user-select: none;
        -ms-user-select:none;
        user-select:none;
      }

      div.grammarly-desktop-integration:before {
        content: attr(data-content);
      }
    </style><div aria-label="grammarly-integration" role="group" tabindex="-1" class="grammarly-desktop-integration" data-content="{&quot;mode&quot;:&quot;limited&quot;,&quot;isActive&quot;:false,&quot;isUserDisabled&quot;:false}"></div></template></grammarly-desktop-integration></html>